/**
 * Centralized Template Registry
 * Single source of truth for all research templates across the application
 */

export interface TemplateDefinition {
  id: string;
  name: string;
  description: string;
  content: string;
  category: 'built-in' | 'custom' | 'vault-file';
  filePath?: string; // For vault-file templates
}

export class TemplateRegistry {
  private static instance: TemplateRegistry | null = null;
  private templates: Map<string, TemplateDefinition> = new Map();
  private app: any; // Obsidian App instance

  private constructor(app?: any) {
    this.app = app;
    this.initializeBuiltInTemplates();
  }

  /**
   * Get singleton instance
   */
  static getInstance(app?: any): TemplateRegistry {
    if (!TemplateRegistry.instance) {
      TemplateRegistry.instance = new TemplateRegistry(app);
    } else if (app && !TemplateRegistry.instance.app) {
      TemplateRegistry.instance.app = app;
    }
    return TemplateRegistry.instance;
  }

  /**
   * Initialize built-in templates
   */
  private initializeBuiltInTemplates(): void {
    // Research Standard Template
    this.templates.set('research-standard', {
      id: 'research-standard',
      name: 'Research Standard',
      description: 'Comprehensive research template with all sections',
      category: 'built-in',
      content: `---
project: "{{projectName}}"
status: "in-progress"
created: "{{today}}"
updated: "{{today}}"
quality: {{qualityScore}}
tags:
  - research/{{researchType}}
{{tags}}
---

# {{title}}

## Overview
{{overview}}

## Properties
{{properties}}

## Research Findings
{{research}}

## Uses & Applications
{{uses}}

## Warnings & Precautions
{{warnings}}

## Sources
{{sources}}

## Related Notes
{{relatedLinks}}

---
*Generated by {{generatedBy}} on {{generationDate}}*
*Search terms: {{searchTerms}}*`
    });

    // Research Minimal Template
    this.templates.set('research-minimal', {
      id: 'research-minimal',
      name: 'Research Minimal',
      description: 'Basic research template with essential sections',
      category: 'built-in',
      content: `---
project: "{{projectName}}"
created: "{{today}}"
tags:
  - research
{{tags}}
---

# {{title}}

## Overview
{{overview}}

## Key Points
{{facts}}

## Sources
{{sources}}`
    });

    // Research Scientific Template
    this.templates.set('research-scientific', {
      id: 'research-scientific',
      name: 'Research Scientific',
      description: 'Academic-style research template with methodology focus',
      category: 'built-in',
      content: `---
project: "{{projectName}}"
status: "in-progress" 
created: "{{today}}"
updated: "{{today}}"
methodology: "systematic-review"
quality: {{qualityScore}}
tags:
  - research/{{researchType}}
  - academic
{{tags}}
---

# {{title}}

## Abstract
{{overview}}

## Introduction
{{definitions}}

## Methods
*Systematic review of vault notes and web sources*

## Results
{{research}}

## Discussion
{{facts}}

## Limitations
{{warnings}}

## Conclusions
{{concepts}}

## References
{{sources}}

---
*Generated by {{generatedBy}} on {{generationDate}}*`
    });
  }

  /**
   * Get all available templates
   */
  getAllTemplates(): TemplateDefinition[] {
    return Array.from(this.templates.values());
  }

  /**
   * Get available templates as dropdown options
   */
  getTemplateOptions(includeCustom: boolean = true): Array<{value: string, text: string}> {
    const options = this.getAllTemplates().map(template => ({
      value: template.id,
      text: `${template.name} - ${template.description}`
    }));

    if (includeCustom) {
      options.push({ value: 'custom', text: 'Custom Template' });
    }

    return options;
  }

  /**
   * Get template by ID
   */
  getTemplate(id: string): TemplateDefinition | null {
    return this.templates.get(id) || null;
  }

  /**
   * Add or update a template
   */
  addTemplate(template: TemplateDefinition): void {
    this.templates.set(template.id, template);
  }

  /**
   * Remove a template (only custom templates can be removed)
   */
  removeTemplate(id: string): boolean {
    const template = this.templates.get(id);
    if (template && template.category === 'custom') {
      return this.templates.delete(id);
    }
    return false;
  }

  /**
   * Get template content with fallback to research-standard
   */
  getTemplateContent(id: string): string {
    const template = this.getTemplate(id);
    if (template) {
      return template.content;
    }
    
    // Fallback to research-standard
    const defaultTemplate = this.getTemplate('research-standard');
    return defaultTemplate ? defaultTemplate.content : '';
  }

  /**
   * Check if template exists
   */
  hasTemplate(id: string): boolean {
    return this.templates.has(id);
  }

  /**
   * Get built-in template IDs
   */
  getBuiltInTemplateIds(): string[] {
    return Array.from(this.templates.values())
      .filter(t => t.category === 'built-in')
      .map(t => t.id);
  }

  /**
   * Get custom template IDs
   */
  getCustomTemplateIds(): string[] {
    return Array.from(this.templates.values())
      .filter(t => t.category === 'custom')
      .map(t => t.id);
  }

  /**
   * Get vault-file template IDs
   */
  getVaultFileTemplateIds(): string[] {
    return Array.from(this.templates.values())
      .filter(t => t.category === 'vault-file')
      .map(t => t.id);
  }

  /**
   * Add a template from a vault file
   */
  async addTemplateFromVaultFile(filePath: string, templateName: string, description?: string): Promise<boolean> {
    if (!this.app || !this.app.vault) {
      console.error('Cannot add vault template: App instance not available');
      return false;
    }

    try {
      // Check if file exists
      const file = this.app.vault.getAbstractFileByPath(filePath);
      if (!file) {
        console.error(`Template file not found: ${filePath}`);
        return false;
      }

      // Read file content
      const content = await this.app.vault.read(file);
      
      // Create template ID from file name
      const templateId = `vault-${filePath.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase()}`;
      
      // Add template to registry
      const template: TemplateDefinition = {
        id: templateId,
        name: templateName || file.basename,
        description: description || `Template from vault file: ${filePath}`,
        content: content,
        category: 'vault-file',
        filePath: filePath
      };

      this.addTemplate(template);
      return true;
    } catch (error) {
      console.error(`Failed to add template from vault file ${filePath}:`, error);
      return false;
    }
  }

  /**
   * Refresh a vault-file template by re-reading from disk
   */
  async refreshVaultFileTemplate(templateId: string): Promise<boolean> {
    const template = this.getTemplate(templateId);
    if (!template || template.category !== 'vault-file' || !template.filePath) {
      return false;
    }

    try {
      const file = this.app.vault.getAbstractFileByPath(template.filePath);
      if (!file) {
        console.error(`Template file no longer exists: ${template.filePath}`);
        return false;
      }

      const content = await this.app.vault.read(file);
      template.content = content;
      this.addTemplate(template);
      return true;
    } catch (error) {
      console.error(`Failed to refresh vault template ${templateId}:`, error);
      return false;
    }
  }

  /**
   * Remove a vault-file template
   */
  removeVaultFileTemplate(templateId: string): boolean {
    const template = this.getTemplate(templateId);
    if (template && template.category === 'vault-file') {
      return this.templates.delete(templateId);
    }
    return false;
  }

  /**
   * Get template content with automatic refresh for vault-file templates
   */
  async getTemplateContentWithRefresh(id: string): Promise<string> {
    const template = this.getTemplate(id);
    if (!template) {
      // Fallback to research-standard
      const defaultTemplate = this.getTemplate('research-standard');
      return defaultTemplate ? defaultTemplate.content : '';
    }

    // Auto-refresh vault-file templates
    if (template.category === 'vault-file') {
      await this.refreshVaultFileTemplate(id);
      const refreshedTemplate = this.getTemplate(id);
      return refreshedTemplate ? refreshedTemplate.content : template.content;
    }

    return template.content;
  }
}